Added 1.14.4 R0.1 support
lishid/Orebfuscator pull request #236
Opened 2019-09-04 21:42 UTC by NgLoader

2019-09-04 21:45 UTC, ProgrammerDan commented
Thank you, will review tonight!

On Wed, Sep 4, 2019 at 5:42 PM NgLoader <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/lishid/Orebfuscator/pull/236
> Commit Summary
>
>    - Added 1.14.4 R0.1 support
>
> File Changes
>
>    - *M* pom.xml
>    <https://github.com/lishid/Orebfuscator/pull/236/files#diff-0> (1)
>    - *A* v1_14_4_R1/pom.xml
>    <https://github.com/lishid/Orebfuscator/pull/236/files#diff-1> (46)
>    - *A*
>    v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/BlockInfo.java
>    <https://github.com/lishid/Orebfuscator/pull/236/files#diff-2> (65)
>    - *A*
>    v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/ChunkCache.java
>    <https://github.com/lishid/Orebfuscator/pull/236/files#diff-3> (99)
>    - *A*
>    v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NBT.java
>    <https://github.com/lishid/Orebfuscator/pull/236/files#diff-4> (65)
>    - *A*
>    v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NmsManager.java
>    <https://github.com/lishid/Orebfuscator/pull/236/files#diff-5> (617)
>
> Patch Links:
>
>    - https://github.com/lishid/Orebfuscator/pull/236.patch
>    - https://github.com/lishid/Orebfuscator/pull/236.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lishid/Orebfuscator/pull/236?email_source=notifications&email_token=AADD5DU2U66O2C2AGNURKQ3QIATVVA5CNFSM4ITWZ2V2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HJL3FZA>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADD5DVOGL6V6H2WGDTYZ53QIATVVANCNFSM4ITWZ2VQ>
> .
>

2019-09-05 03:38 UTC, ProgrammerDan commented
Broad strokes are OK, some details to fine tune -- do you figure you are done with this contribution or do you intend to work on it more? Regardless, thanks for this contribution, will blend with the prior PR, alongside some additional work I intend to begin soon to figure out the longstanding bugs.

2019-09-05 04:56 UTC, ProgrammerDan requested changes
Some minor changes, some stuff to double check -- thanks for contributing!

2019-09-05 04:56 UTC, ProgrammerDan commented on Plugin/pom.xml
>      <dependency>
It's likely the POM will need some other changes. The prior PR #235 had the right idea in some places, esp the version increase (although preserve the -SNAPSHOT -- I remove that for releases alone).

2019-09-05 04:56 UTC, ProgrammerDan commented on pom.xml
> +    <module>v1_14_4_R1</module>
Module should be v1_14_R1 -- so far as I can see there are no API changes, just fix releases, so it's just v1_14_R1.

2019-09-05 04:56 UTC, ProgrammerDan commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/BlockInfo.java
> +package com.lishid.orebfuscator.nms.v1_14_2_R1;
package and folder should be v1_14_R1, or at the least, consistent with base folder.

2019-09-05 04:56 UTC, ProgrammerDan commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/ChunkCache.java
> +                	// This lovely piece of work is due to an NMS change in Spigot 1.13.2 without an R increase.
Due to release of obfuscation mapping, I can confidently describe that this extra handler is unnecessary for 1.14, and can be reduce to just the "close" method retrieval and invocation. (line 38987 in the server deobfuscation for 1.14).

2019-09-05 04:56 UTC, ProgrammerDan commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NmsManager.java
> +		// like in ChunkCache, NMS change without R increment.
will have to investigate bukkit here to see which of the following Methods needs to remain

2019-09-05 04:56 UTC, ProgrammerDan commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NmsManager.java
> +	private static final int BITS_PER_BLOCK = 14;
Not 100% sure but indicators I use, indicate that this bits per block is still 14, so good news there

2019-09-05 04:56 UTC, ProgrammerDan commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NmsManager.java
> +				Material.YELLOW_WALL_BANNER
Some good expansion here

2019-09-05 04:56 UTC, ProgrammerDan commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NmsManager.java
> +			Method getTileEntityAt = world.getClass().getMethod("getTileEntityAt", int.class, int.class, int.class);
Will have to reference craftbukkit impl to see which one is current for 1.14

2019-09-05 04:56 UTC, ProgrammerDan commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NmsManager.java
> +		return Block.getByCombinedId(combinedBlockId).getBlock().isTileEntity();
Hopefully the combinedID business still works. Will review.

2019-09-05 10:51 UTC, NgLoader commented
I commit some changes soon 👍

2019-09-05 19:43 UTC, NgLoader commented
Currently I'm looking into the ArrayIndexOutOfBoundsException error

2019-09-20 14:56 UTC, ProgrammerDan commented
Any updates here, friend?

2019-11-11 21:48 UTC, Chevels commented
Any news ? Or OFC is definitively abandonned ? :/

2019-11-11 21:53 UTC, ProgrammerDan commented
Nothing new from the contributor of this PR, and as for me I haven't had much time for any of my projects. Not officially abandoned but I would welcome dedicated help.

2019-11-21 21:04 UTC, SydMontague commented
I tested the branch locally and it didn't work properly. After some digging I figured out it's because of a protocol change the code doesn't attribute for.
(In detail: light information is not transmitted anymore and a non-air block count field has been introduced)

Based on NgLoader's work I wrote a patch that should make it 1.14.4 compatible, it worked on my local test server but that by no means indicates full compatibility. The patch shouldn't be backward compatible either, so for that some more work is required.

[Orebfuscator114.patch.txt](https://github.com/lishid/Orebfuscator/files/3876734/Orebfuscator114.patch.txt)

2019-11-21 21:22 UTC, ProgrammerDan commented
Nice, thank you. Will try to do some testing / integration -- would welcome
a full pr as well.

On Thu, Nov 21, 2019 at 4:04 PM SydMontague <notifications@github.com>
wrote:

> I tested the branch locally and it didn't work properly. After some
> digging I figured out it's because of a protocol change the code doesn't
> attribute for.
> (In detail: light information is not transmitted anymore and a non-air
> block count field has been introduced)
>
> Based on NgLoader's work I wrote a patch that should make it 1.14.4
> compatible, it worked on my local test server but that by no means
> indicates full compatibility. The patch shouldn't be backward compatible
> either, so for that some more work is required.
>
> Orebfuscator114.patch.txt
> <https://github.com/lishid/Orebfuscator/files/3876734/Orebfuscator114.patch.txt>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lishid/Orebfuscator/pull/236?email_source=notifications&email_token=AADD5DRU6EFJUG4MKJSN3YDQU3ZWHA5CNFSM4ITWZ2V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE3URIQ#issuecomment-557271202>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADD5DUB7HEQUFOI6JQKWYDQU3ZWHANCNFSM4ITWZ2VQ>
> .
>

2019-11-30 11:03 UTC, NgLoader commented
I commit some changes soon.
Currently is my pc away for a upgrade.

Thanks @SydMontague

2019-11-30 11:06 UTC, NgLoader commented
And @Sydmontague you can commit on my frok so you don't need to send a txt file with changes 😅

2019-11-30 11:46 UTC, NgLoader commented
I moved the project to a new location
[Repo](https://github.com/TeamWuffy/Orebfuscator)

2019-11-30 13:14 UTC, SydMontague commented
I created a pull request to your repo and also fixed some more issues. The NmsManager did some obsolete reflection that caused the plugin to not work properly in the Nether. In the process I also found a potential NPE I prevented with a simple null check.

The changes I made should now also be backwards compatible...

2019-12-08 09:48 UTC, NgLoader commented
Its working for me too, you can test the version [here](https://github.com/TeamWuffy/Orebfuscator/releases/latest)

2019-12-08 21:07 UTC, NgLoader commented on v1_14_4_R1/src/main/java/com/lishid/orebfuscator/nms/v1_14_2_R1/NmsManager.java
> +				Material.YELLOW_WALL_BANNER
currently not, sry

2019-12-15 06:25 UTC, NgLoader commented
1.15 update coming soon :smile: currently testing works fine

2019-12-29 09:21 UTC, closed without merging

2020-06-26 17:26 UTC, Miky88 commented
rip why closed

2020-06-26 17:39 UTC, NgLoader commented
The project was moved to Imprex-Development for 1.8-1.15 support.
1.16 ist currently in progress